[build]
publish = "distill_static"
command = "python manage.py distill-local distill_static --force"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
